### ISSUE TITLE
`npm run start` Failed

### ISSUE THREAD

**Issue by emadurandal** [GianlucaGuarini/riot-app-example#3]
Thank you about #2 
I success to npm install.
But `npm run start` failed in this time.

```
emadurandal@Yuki-no-MBP:~/ESDocs/Programs/_Sites/riot_ex/riot-app-example (master)
$ npm run start

> riot-app-example@1.0.0 start /Users/emadurandal/ESDocs/Programs/_Sites/riot_ex/riot-app-example
> babel-node --presets es2015 -- server/index.js

Example app listening at http://localhost:3000
/Users/emadurandal/ESDocs/Programs/_Sites/riot_ex/riot-app-example/shared/components/src/app.tag:2
import './layout/sidebar.tag'
^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.require.extensions..tag (/Users/emadurandal/ESDocs/Programs/_Sites/riot_ex/riot-app-example/node_modules/riot/lib/server/index.js:15:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at index.js:36:5
    at Array.forEach (native)
    at index.js:35:8

npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/emadurandal/.nodebrew/node/v4.4.0/bin/node" "/Users/emadurandal/.nodebrew/current/bin/npm" "run" "start"
npm ERR! node v4.4.0
npm ERR! npm  v3.8.2
npm ERR! code ELIFECYCLE
npm ERR! riot-app-example@1.0.0 start: `babel-node --presets es2015 -- server/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the riot-app-example@1.0.0 start script 'babel-node --presets es2015 -- server/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the riot-app-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node --presets es2015 -- server/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs riot-app-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls riot-app-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/emadurandal/ESDocs/Programs/_Sites/riot_ex/riot-app-example/npm-debug.log
```

**Comment by GianlucaGuarini** [comment]
I think something went wrong installing `babel-node` try the following steps:
1. delete the `node_modules` folder
2. Reinstall the npm modules `$ sudo npm install`
3. Build the project `$ npm run build`
4. Run the server `$ npm start`

Let me know if it works please

**Comment by emadurandal** [comment]
Thanks for your reply.
I did do that. But `$npm start` failed again. same error.
Please check again.

(node v4.4.0, npm  v3.8.2)

**Comment by GianlucaGuarini** [comment]
@emadurandal I am sorry now everything should be fine

**Comment by emadurandal** [comment]
@GianlucaGuarini I checked everything work fine. thank you!
